export default function Head() {
  return (
    <>
      <title>Jobet&apos;s Portfolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.svg" type="image/svg+xml" className="#4d5b8a"/>
    </>
  )
}